<?php
/**
 * Seeds the wp-env site so the plugin is testable in one step.
 *
 * Run through WP-CLI, not the web: `npm run env:setup`.
 *
 * Reads the public key generated by `npm run webhook:keygen` straight off the
 * mounted repo, so the key never has to survive shell quoting on its way into
 * the container.
 *
 * @package Afriex_Gateway_For_WooCommerce
 */

if ( ! defined( 'WP_CLI' ) || ! WP_CLI ) {
	return;
}

$key_path = __DIR__ . '/.keys/public.pem';

if ( ! file_exists( $key_path ) ) {
	WP_CLI::error( 'No public key at tests/tools/.keys/public.pem. Run: npm run webhook:keygen' );
}

$public_key = trim( file_get_contents( $key_path ) ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents

update_option(
	'woocommerce_afriex_settings',
	array(
		'enabled'            => 'yes',
		'title'              => 'Bank Transfer',
		'description'        => 'Pay by bank transfer. You will receive account details after placing your order.',
		'instructions'       => 'Transfer the exact order total to the account below.',
		'environment'        => 'staging',
		// Any non-empty value: is_available() only checks that a key is set, and
		// these tests drive the webhook path rather than live API calls.
		'api_key'            => 'test-api-key',
		'webhook_public_key' => $public_key,
		'collection_method'  => 'dedicated',
		'logging'            => 'yes',
	)
);

WP_CLI::log( 'Gateway settings seeded (enabled, logging on, public key loaded).' );

update_option( 'woocommerce_currency', 'NGN' );
update_option( 'woocommerce_default_country', 'NG' );
update_option( 'woocommerce_store_address', '1 Test Street' );
update_option( 'woocommerce_store_city', 'Lagos' );

// Skip the setup wizard so checkout is reachable immediately.
update_option( 'woocommerce_onboarding_profile', array( 'completed' => true ) );

WP_CLI::log( 'Store configured: NGN, Nigeria.' );

$existing = wc_get_products(
	array(
		'limit'  => 1,
		'status' => 'publish',
	)
);

if ( empty( $existing ) ) {
	$product = new WC_Product_Simple();
	$product->set_name( 'Afriex Test Product' );
	$product->set_regular_price( '49.99' );
	$product->set_catalog_visibility( 'visible' );
	$product->set_status( 'publish' );
	$product->set_virtual( true );
	$product->save();

	WP_CLI::log( 'Created test product #' . $product->get_id() . ' at 49.99.' );
} else {
	WP_CLI::log( 'Product already present (#' . $existing[0]->get_id() . '), leaving it alone.' );
}

WP_CLI::success( 'Seed complete. Place an order, then read its _afriex_payment_method_id to drive the webhook tool.' );
